<?xml version="1.0" encoding="UTF-8"?>
<!-- Service -->
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:xs="http://www.w3.org/2001/XMLSchema"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:ns="http://schemas.xmlsoap.org/soap/encoding/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:osci="http://www.osci.de/2006/07/wsdl/"
             xmlns:tpl="http://www.dvdv.de/dvdv/template/"
             xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
             xmlns:tns="http://www.osci.de/xmeld243/xmeld243Wehrverwaltung.wsdl"
             xmlns:xmeld="http://www.osci.de/xmeld243"
             name="xmeld243Wehrverwaltung"
             targetNamespace="http://www.osci.de/xmeld243/xmeld243Wehrverwaltung.wsdl"
             xsi:schemaLocation="http://schemas.xmlsoap.org/wsdl/ http://schemas.xmlsoap.org/wsdl/">
   <documentation><![CDATA[<html><head><title>Dienst der Wehrverwaltung gemäß OSCI-XMeld</title></head><body><h1>Dienst der Wehrverwaltung gemäß OSCI-XMeld</h1><p>Dieses WSDL-Dokument beschreibt den Dienst der Wehrverwaltung gemäß OSCI-XMeld (siehe: <link>http://www.osci.de</link>).</p><p>Folgende Datenübermittlungs-Nachrichten des XMeld-Schemas sind als Input der einzigen Operation <i>sendeDatenuebermittlung</i> zulässig:<ul><ul>
            <li>xmeld:datenuebermittlung.wehrverwaltungvolljaehrigkeit.0557</li>
         </ul></ul></p><p>Behördenschlüssel für <i>find.servicedescription</i>-Anfragen ist der zwölfstellige DVDV-Schlüssel "dbs:490050010000"; der zu verwendende Präfix lautet "<b>dbs:</b>". </p><p>Dienstanbieter ist die Wehrverwaltung, DVDV-Behördenkategorie "<b>Bundesbehörde</b>". Zulässige Dienstnutzer sind ausschließlich Behörden der DVDV-Behördenkategorie "<b>Meldebehörde</b>". Anfragen ans DVDV vom Typ <i>verify.category</i> sollten daher die Zuordnung zu dieser Kategorie prüfen lassen.</p></body></html>]]></documentation>
   <import namespace="http://www.osci.de/2006/07/wsdl/"
           location="http://www.osci.de/wsdl-osci-binding/WSDL-OSCI-Binding_1.2.xsd"/>
   <import namespace="http://www.osci.de/xmeld243"
           location="http://www.osci.de/xmeld243/xmeld-nachrichten-datenuebermittlung.xsd"/>
   <message name="wehrverwaltungNachricht">
      <part name="wehrverwaltungNachricht"
            element="xmeld:datenuebermittlung.wehrverwaltungvolljaehrigkeit.0557"/>
      <part name="optionaleNachricht" type="xs:anyType"/>
   </message>
   <portType name="osciWehrverwaltungInterface">
      <operation name="sendeWehrverwaltung">
         <input message="tns:wehrverwaltungNachricht"/>
      </operation>
   </portType>
   <binding name="osciBinding" type="tns:osciWehrverwaltungInterface">
      <osci:binding signatureLevel="none" encrypted="true">
         <osci:reader name="Inhaltsdaten-Verschlüsselungszertifikat">
            <tpl:certificate/>
         </osci:reader>
      </osci:binding>
      <!-- Vorbelegung der Richtlinien zur Signatur und Verschlüsselung der Nutzdaten für alle Operationen -->
      <operation name="sendeWehrverwaltung">
         <osci:operation communicationType="one-way-active" subject="XMeld 2.4.3 Wehrverwaltung"/>
         <input>
            <osci:container signatureLevel="advanced"
                            encrypted="true"
                            name="XMELD_DATA"
                            required="true">
               <osci:readerRef ref="Inhaltsdaten-Verschlüsselungszertifikat"/>
               <osci:part>
                  <osci:content part="tns:wehrverwaltungNachricht"/>
               </osci:part>
            </osci:container>
            <osci:container signatureLevel="none" encrypted="false" required="false">
               <osci:part>
                  <osci:content part="tns:optionaleNachricht"/>
               </osci:part>
            </osci:container>
         </input>
      </operation>
   </binding>
   <service name="osciWehrverwaltungService"><!-- OSCI Infrastrukturserver -->
      <osci:devices>
         <osci:intermediary uri="" name="InternetIntermediär">
            <osci:signatureCertificate>
               <tpl:certificate/>
            </osci:signatureCertificate>
            <osci:cipherCertificate>
               <tpl:certificate/>
            </osci:cipherCertificate>
         </osci:intermediary>
         <osci:intermediary uri="" name="TESTAIntermediär">
            <osci:signatureCertificate>
               <tpl:certificate/>
            </osci:signatureCertificate>
            <osci:cipherCertificate>
               <tpl:certificate/>
            </osci:cipherCertificate>
         </osci:intermediary>
         <osci:addressee name="InternetEmpfänger">
            <osci:cipherCertificate>
               <tpl:certificate/>
            </osci:cipherCertificate>
         </osci:addressee>
         <osci:addressee name="TESTAEmpfänger">
            <osci:cipherCertificate>
               <tpl:certificate/>
            </osci:cipherCertificate>
         </osci:addressee>
      </osci:devices>
      <!-- Endpunkt im Internet -->
      <port name="osciWehrverwaltungInternetPort" binding="tns:osciBinding">
         <documentation>
            <tpl:use>required</tpl:use> Dieser Port ist nicht optional </documentation>
         <osci:address>
            <osci:intermediaryRef ref="InternetIntermediär"/>
            <osci:addresseeRef ref="InternetEmpfänger"/>
         </osci:address>
      </port>
      <!-- Endpunkt im TESTA -->
      <port name="osciWehrverwaltungTestaPort" binding="tns:osciBinding">
         <documentation>
            <tpl:use>optional</tpl:use> Dieser Port ist optional </documentation>
         <osci:address>
            <osci:intermediaryRef ref="TESTAIntermediär"/>
            <osci:addresseeRef ref="TESTAEmpfänger"/>
         </osci:address>
      </port>
   </service>
</definitions>
