<?xml version="1.0" encoding="UTF-8"?>
<!-- Service -->
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:xs="http://www.w3.org/2001/XMLSchema"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:ns="http://schemas.xmlsoap.org/soap/encoding/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:osci="http://www.osci.de/2006/07/wsdl/"
             xmlns:tpl="http://www.dvdv.de/dvdv/template/"
             xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
             xmlns:tns="http://www.osci.de/xmeld243/xmeld243Quittung.wsdl"
             xmlns:xmeld="http://www.osci.de/xmeld243"
             name="xmeld243Quittung"
             targetNamespace="http://www.osci.de/xmeld243/xmeld243Quittung.wsdl"
             xsi:schemaLocation="http://schemas.xmlsoap.org/wsdl/ http://schemas.xmlsoap.org/wsdl/">
   <documentation><![CDATA[<html><head><title>Dienst für Quittungs- und Quittierungs-Nachrichten unterschiedlicher Kommunikationspartner gemäß OSCI-XMeld</title></head><body><h1>Dienst für Quittierungs-Nachrichten unterschiedlicher Kommunikationspartner gemäß OSCI-XMeld</h1><p>Dieses WSDL-Dokument beschreibt den Dienst für Quittungs- und Quittierungs-Nachrichten unterschiedlicher Kommunikationspartner gemäß OSCI-XMeld (siehe: <link>http://www.osci.de</link>).</p><p>Folgende Quittungs- und Quittierungs-Nachrichten des XMeld-Schemas sind als Input der einzigen Operation <i>sendeAdministrationsnachricht</i> zulässig:<ul><ul>
            <li>xmeld:administration.quittierungbestandslieferung.0928</li>
         </ul></ul></p><p>Behördenschlüssel für <i>find.servicedescription</i>-Anfragen unterscheiden sich je nach Kommunikationspartner. Bspw. ist für Quittungs- und Quittierungs-Nachrichten an Meldebehörden der achtstellige Amtliche Gemeindeschlüssel (AGS) mit dem Präfix <b>ags:</b> zu verwenden.</p><p>Zulässige Dienstanbieter sind alle Kommunikationspartner im Informationsverbund des Meldewesens. Die zulässigen Dienstnutzer sind abhängig vom Nachrichtentyp.</p></body></html>]]></documentation>
   <import namespace="http://www.osci.de/2006/07/wsdl/"
           location="http://www.osci.de/wsdl-osci-binding/WSDL-OSCI-Binding_1.2.xsd"/>
   <import namespace="http://www.osci.de/xmeld243"
           location="http://www.osci.de/xmeld243/xmeld-nachrichten-administration.xsd"/>
   <message name="quittungNachricht">
      <part name="quittungNachricht"
            element="xmeld:administration.quittierungbestandslieferung.0928"/>
      <part name="optionaleNachricht" type="xs:anyType"/>
   </message>
   <portType name="osciQuittungInterface">
      <operation name="sendeQuittung">
         <input message="tns:quittungNachricht"/>
      </operation>
   </portType>
   <binding name="osciBinding" type="tns:osciQuittungInterface">
      <osci:binding signatureLevel="none" encrypted="true">
         <osci:reader name="Inhaltsdaten-Verschlüsselungszertifikat">
            <tpl:certificate/>
         </osci:reader>
      </osci:binding>
      <!-- Vorbelegung der Richtlinien zur Signatur und Verschlüsselung der Nutzdaten für alle Operationen -->
      <operation name="sendeQuittung">
         <osci:operation communicationType="one-way-active" subject="XMeld 2.4.3 Quittung"/>
         <input>
            <osci:container signatureLevel="advanced"
                            encrypted="true"
                            name="XMELD_DATA"
                            required="true">
               <osci:readerRef ref="Inhaltsdaten-Verschlüsselungszertifikat"/>
               <osci:part>
                  <osci:content part="tns:quittungNachricht"/>
               </osci:part>
            </osci:container>
            <osci:container signatureLevel="none" encrypted="false" required="false">
               <osci:part>
                  <osci:content part="tns:optionaleNachricht"/>
               </osci:part>
            </osci:container>
         </input>
      </operation>
   </binding>
   <service name="osciQuittungService"><!-- OSCI Infrastrukturserver -->
      <osci:devices>
         <osci:intermediary uri="" name="InternetIntermediär">
            <osci:signatureCertificate>
               <tpl:certificate/>
            </osci:signatureCertificate>
            <osci:cipherCertificate>
               <tpl:certificate/>
            </osci:cipherCertificate>
         </osci:intermediary>
         <osci:intermediary uri="" name="TESTAIntermediär">
            <osci:signatureCertificate>
               <tpl:certificate/>
            </osci:signatureCertificate>
            <osci:cipherCertificate>
               <tpl:certificate/>
            </osci:cipherCertificate>
         </osci:intermediary>
         <osci:addressee name="InternetEmpfänger">
            <osci:cipherCertificate>
               <tpl:certificate/>
            </osci:cipherCertificate>
         </osci:addressee>
         <osci:addressee name="TESTAEmpfänger">
            <osci:cipherCertificate>
               <tpl:certificate/>
            </osci:cipherCertificate>
         </osci:addressee>
      </osci:devices>
      <!-- Endpunkt im Internet -->
      <port name="osciQuittungInternetPort" binding="tns:osciBinding">
         <documentation>
            <tpl:use>required</tpl:use> Dieser Port ist nicht optional </documentation>
         <osci:address>
            <osci:intermediaryRef ref="InternetIntermediär"/>
            <osci:addresseeRef ref="InternetEmpfänger"/>
         </osci:address>
      </port>
      <!-- Endpunkt im TESTA -->
      <port name="osciQuittungTestaPort" binding="tns:osciBinding">
         <documentation>
            <tpl:use>optional</tpl:use> Dieser Port ist optional </documentation>
         <osci:address>
            <osci:intermediaryRef ref="TESTAIntermediär"/>
            <osci:addresseeRef ref="TESTAEmpfänger"/>
         </osci:address>
      </port>
   </service>
</definitions>
